<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\MatchMaking.Infrastructure.Redis\MatchMaking.Infrastructure.Redis.csproj" />
      <ProjectReference Include="..\MatchMaking.Service.BLCore\MatchMaking.Service.BLCore.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
      <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
      <PackageReference Include="Serilog.Expressions" Version="5.0.0" />
      <PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
      <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
    </ItemGroup>

</Project>
